"""
Type stubs for analyze
Auto-generated by generate_stubs.py
"""

from typing import Optional, List, Tuple, Any
import numpy as np
import numpy.typing as npt

# Type aliases
Frame = npt.NDArray[np.uint8]  # BGRA image array
Color = Tuple[int, int, int]   # BGR color tuple

class analyze:
    """Analyze frame"""

    @staticmethod
    def diagram_visualize(frame: Frame) -> Frame: ...
