"""
Type stubs for blend
Auto-generated by generate_stubs.py
"""

from typing import Optional, List, Tuple, Any
import numpy as np
import numpy.typing as npt

# Type aliases
Frame = npt.NDArray[np.uint8]  # BGRA image array
Color = Tuple[int, int, int]   # BGR color tuple

class blend:
    """Blend and composite multiple frames"""

    @staticmethod
    def alpha(frame1: Frame, frame2: Frame, alpha: float = 0.5) -> Optional[Frame]: ...

    @staticmethod
    def add(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def subtract(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def difference(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def multiply(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def screen(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def overlay(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def lighten(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def darken(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def average(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def max(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def min(frame1: Frame, frame2: Frame) -> Optional[Frame]: ...

    @staticmethod
    def history_average(history: List[Frame]) -> Optional[Frame]: ...

    @staticmethod
    def history_weighted(history: List[Frame], weights: Optional[Any] = None) -> Optional[Frame]: ...

    @staticmethod
    def history_max(history: List[Frame]) -> Optional[Frame]: ...

    @staticmethod
    def history_min(history: List[Frame]) -> Optional[Frame]: ...

    @staticmethod
    def history_median(history: List[Frame]) -> Optional[Frame]: ...

    @staticmethod
    def history_diff_sum(history: List[Frame]) -> Optional[Frame]: ...

    @staticmethod
    def history_trail(history: List[Frame], decay: float = 0.9) -> Optional[Frame]: ...

    @staticmethod
    def history_onion_skin(history: List[Frame], count: int = 5, alpha: float = 0.3) -> Optional[Frame]: ...

    @staticmethod
    def history_echo(history: List[Frame], indices: List = [0, 5, 10], weights: Optional[Any] = None) -> Optional[Frame]: ...
