"""
Type stubs for draw
Auto-generated by generate_stubs.py
"""

from typing import Optional, List, Tuple, Any
import numpy as np
import numpy.typing as npt

# Type aliases
Frame = npt.NDArray[np.uint8]  # BGRA image array
Color = Tuple[int, int, int]   # BGR color tuple

class draw:
    """Drawing graphics on frames"""

    @staticmethod
    def rectangle(frame: Frame, x1: int = 50, y1: int = 50, x2: int = 200, y2: int = 150, color: Color = (0, 255, 0), thickness: int = 2) -> Frame: ...

    @staticmethod
    def circle(frame: Frame, cx: int = 320, cy: int = 240, radius: int = 50, color: Color = (0, 0, 255), thickness: Any = -1) -> Frame: ...

    @staticmethod
    def line(frame: Frame, x1: int = 0, y1: int = 0, x2: int = 640, y2: int = 480, color: Color = (255, 255, 255), thickness: int = 2) -> Frame: ...

    @staticmethod
    def crosshair(frame: Frame, cx: Optional[Any] = None, cy: Optional[Any] = None, size: int = 20, color: Color = (0, 255, 0), thickness: int = 1) -> Frame: ...

    @staticmethod
    def polygon(frame: Frame, points: Optional[Any] = None, color: Color = (255, 0, 255), thickness: int = 2, filled: bool = False) -> Frame: ...

    @staticmethod
    def ellipse(frame: Frame, cx: int = 320, cy: int = 240, width: int = 100, height: int = 50, angle: int = 0, start_angle: int = 0, end_angle: int = 360, color: Color = (255, 128, 0), thickness: int = 2) -> Frame: ...

    @staticmethod
    def text(frame: Frame, text: str = "Hello World", x: int = 100, y: int = 100, font_scale: float = 1.0, color: Color = (255, 255, 255), thickness: int = 2, bg_color: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def grid(frame: Frame, spacing: int = 50, color: Color = (100, 100, 100), thickness: int = 1) -> Frame: ...

    @staticmethod
    def colorize_edges(frame: Frame, threshold1: int = 50, threshold2: int = 150, color: Color = (0, 255, 0)) -> Frame: ...
