"""
Type stubs for generate
Auto-generated by generate_stubs.py
"""

from typing import Optional, List, Tuple, Any
import numpy as np
import numpy.typing as npt

# Type aliases
Frame = npt.NDArray[np.uint8]  # BGRA image array
Color = Tuple[int, int, int]   # BGR color tuple

class generate:
    """Generate new frames from scratch"""

    @staticmethod
    def solid(width: int = 640, height: int = 480, color: Color = (0, 0, 0), frame: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def noise_uniform(width: int = 640, height: int = 480, frame: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def noise_gaussian(width: int = 640, height: int = 480, mean: int = 128, stddev: int = 50, frame: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def gradient_horizontal(width: int = 640, height: int = 480, color1: Color = (0, 0, 0), color2: Color = (255, 255, 255), frame: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def gradient_vertical(width: int = 640, height: int = 480, color1: Color = (0, 0, 0), color2: Color = (255, 255, 255), frame: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def gradient_radial(width: int = 640, height: int = 480, color1: Color = (0, 0, 0), color2: Color = (255, 255, 255), frame: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def checkerboard(width: int = 640, height: int = 480, square_size: int = 40, color1: Color = (0, 0, 0), color2: Color = (255, 255, 255), frame: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def stripes_horizontal(width: int = 640, height: int = 480, stripe_height: int = 40, color1: Color = (0, 0, 0), color2: Color = (255, 255, 255), frame: Optional[Any] = None) -> Frame: ...

    @staticmethod
    def stripes_vertical(width: int = 640, height: int = 480, stripe_width: int = 40, color1: Color = (0, 0, 0), color2: Color = (255, 255, 255), frame: Optional[Any] = None) -> Frame: ...
