"""
Type stubs for process
Auto-generated by generate_stubs.py
"""

from typing import Optional, List, Tuple, Any
import numpy as np
import numpy.typing as npt

# Type aliases
Frame = npt.NDArray[np.uint8]  # BGRA image array
Color = Tuple[int, int, int]   # BGR color tuple

class process:
    """Image processing and transformation effects"""

    @staticmethod
    def grayscale(frame: Frame) -> Frame: ...

    @staticmethod
    def invert(frame: Frame) -> Frame: ...

    @staticmethod
    def brighten(frame: Frame, value: int = 50) -> Frame: ...

    @staticmethod
    def contrast(frame: Frame, alpha: float = 1.5) -> Frame: ...

    @staticmethod
    def adjust_contrast_brightness(frame: Frame, contrast: float = 1.5, brightness: int = 30) -> Frame: ...

    @staticmethod
    def blur_gaussian(frame: Frame, kernel_size: int = 5, sigma: int = 0) -> Frame: ...

    @staticmethod
    def blur_median(frame: Frame, kernel_size: int = 15) -> Frame: ...

    @staticmethod
    def blur_box(frame: Frame, kernel_size: int = 10) -> Frame: ...

    @staticmethod
    def blur_bilateral(frame: Frame, diameter: int = 9, sigma_color: int = 75, sigma_space: int = 75) -> Frame: ...

    @staticmethod
    def edge_canny(frame: Frame, threshold1: int = 50, threshold2: int = 150) -> Frame: ...

    @staticmethod
    def edge_laplacian(frame: Frame) -> Frame: ...

    @staticmethod
    def edge_sobel(frame: Frame, dx: int = 1, dy: int = 0, ksize: int = 3) -> Frame: ...

    @staticmethod
    def threshold_binary(frame: Frame, thresh_value: int = 127) -> Frame: ...

    @staticmethod
    def threshold_adaptive(frame: Frame, block_size: int = 11, c: int = 2) -> Frame: ...

    @staticmethod
    def erode(frame: Frame, kernel_size: int = 3, iterations: int = 1) -> Frame: ...

    @staticmethod
    def dilate(frame: Frame, kernel_size: int = 3, iterations: int = 1) -> Frame: ...

    @staticmethod
    def morph_open(frame: Frame, kernel_size: int = 5, iterations: int = 1) -> Frame: ...

    @staticmethod
    def morph_close(frame: Frame, kernel_size: int = 5, iterations: int = 1) -> Frame: ...

    @staticmethod
    def flip_horizontal(frame: Frame) -> Frame: ...

    @staticmethod
    def flip_vertical(frame: Frame) -> Frame: ...

    @staticmethod
    def rotate_90(frame: Frame) -> Frame: ...

    @staticmethod
    def rotate_angle(frame: Frame, angle: int = 45) -> Frame: ...

    @staticmethod
    def equalize_histogram(frame: Frame) -> Frame: ...

    @staticmethod
    def stylize(frame: Frame, sigma_s: int = 60, sigma_r: float = 0.6) -> Frame: ...

    @staticmethod
    def pencil_sketch(frame: Frame, sigma_s: int = 60, sigma_r: float = 0.07, shade_factor: float = 0.05) -> Frame: ...

    @staticmethod
    def edge_preserving_filter(frame: Frame, sigma_s: int = 60, sigma_r: float = 0.4) -> Frame: ...

    @staticmethod
    def convert_hsv(frame: Frame) -> Frame: ...

    @staticmethod
    def shift_hue(frame: Frame, shift: int = 90) -> Frame: ...

    @staticmethod
    def remove_channel(frame: Frame, channel: int = 0) -> Frame: ...

    @staticmethod
    def posterize(frame: Frame, levels: int = 4) -> Frame: ...

    @staticmethod
    def pixelate(frame: Frame, pixel_size: int = 10) -> Frame: ...

    @staticmethod
    def glitch(frame: Frame, intensity: int = 20) -> Frame: ...

    @staticmethod
    def channel_threshold(frame: Frame, threshold: int = 128) -> Frame: ...

    @staticmethod
    def scanlines(frame: Frame, line_spacing: int = 2, line_intensity: float = 0.5) -> Frame: ...

    @staticmethod
    def chromatic_aberration(frame: Frame, offset: int = 5) -> Frame: ...

    @staticmethod
    def vignette(frame: Frame, intensity: float = 0.5) -> Frame: ...

    @staticmethod
    def datamosh(frame: Frame, block_size: int = 8, corruption: float = 0.3) -> Frame: ...

    @staticmethod
    def add_noise_uniform(frame: Frame, amount: int = 50) -> Frame: ...

    @staticmethod
    def add_noise_gaussian(frame: Frame, mean: int = 0, stddev: int = 25) -> Frame: ...

    @staticmethod
    def invert_channels(frame: Frame, b_invert: int = 255, g_invert: int = 255, r_invert: int = 255) -> Frame: ...

    @staticmethod
    def swap_channels(frame: Frame, order: str = "rbg") -> Frame: ...

    @staticmethod
    def edge_masked(frame: Frame, threshold1: int = 100, threshold2: int = 200) -> Frame: ...
